aproject/urls.py
# from django.contrib import admin
# from django.urls import path

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import include, path
from django.shortcuts import redirect

def root(request):
    # TODO: 차후에 URL Reverse 기능
   # return HttpResponseRedirect('/blog/')
   return redirect('shop:index')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('', root),
]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, re_path
from blog.views import index, hello_times
# from blog.views import articles_by_year
from blog.views import naver_realtime_keywords
from blog.views import naver_blog_search
from blog.views import 사원증_이미지_응답

from django.urls import register_converter
# from blog.converters import FourDigitYearConverter
# from blog.converters import SlugUnicodeConverter

# register_converter(FourDigitYearConverter, 'year')
# register_converter(SlugUnicodeConverter, 'slug_unicode')


app_name = 'blog'  # URL Reverse 기능을 할 때, 사용.


urlpatterns = [
    # path('articles/<year:year>/', articles_by_year),

    # re_path('^blog/1/$', post_detail),
    # re_path('^blog/1/edit/$', post_edit),

    path('', index),
    # re_path(r'^$', index),

    path('hello_times/<int:times>/', hello_times),
    # re_path(r'blog/hello_times/(?P<times>\d+)/$', hello_times),

    path('naver/실시간검색어/', naver_realtime_keywords),
    path('naver/네이버블로그검색/', naver_blog_search),

    path('사원증/', 사원증_이미지_응답),
]

shop/urls.py
# from django.urls import path
# from . import views

# app_name = 'shop'

# urlpatterns = [
#     path('', views.index),
#     path('<int:pk>/', views.shop_detail),
#     path('new/', views.shop_new),
#     path('new_cbv/', views.shop_new_cbv),
#     path('<int:pk>/edit/', views.shop_edit),
#     path('<int:pk>/edit/', views.shop_edit_cbv),
#     # path('<int:pk>/delete/', views.shop_delete),
# ]

from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.shop_detail, name='shop_detail'),
    path('new/', views.shop_new, name='shop_new'),
    path('new_cbv/', views.shop_new_cbv, name='shop_new_cbv'),
    path('<int:pk>/edit/', views.shop_edit, name='shop_edit'),
    path('<int:pk>/edit_cbv/', views.shop_edit_cbv, name='shop_edit_cbv'),
    path('<int:pk>/delete/', views.shop_delete,name ='shop_delete'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Shop(models.Model):
    name = models.CharField(max_length=100)
    photo = models.ImageField(blank=True)
    desc = models.TextField(blank=True)
    address = models.CharField(max_length=100, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # return "/shop/{}/".format(self.id)
        return reverse("shop:shop_detail", args=[self.id])
        # return reverse("shop:shop_detail", kwargs={'pk': self.id})


class Item(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    desc = models.TextField(blank=True)
    price = models.PositiveIntegerField()
    is_public = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

shop/forms.py
# File name: shop/forms.py

from django import forms
from .models import Shop


class ShopForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = '__all__'  # 모든 필드 가져오기
        # fields = ['title', 'content']  # 지정 필드만 가져오기

shop/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .models import Shop
from .forms import ShopForm


# def index(request):
#     # 전체 Shop 목록을 가져올 예정이다. (Lazy한 특성)
#     qs = Shop.objects.all()
#     return render(request, 'shop/shop_list.html', {
#         'shop_list': qs,
#     })

class PostListView(ListView):
    model = Shop

    def get_context_data(self):
        context = super().get_context_data()
        context.update({
            'hello': 'world',
        })
        return context

index = PostListView.as_view()


# def shop_detail(request, pk):
#     # 즉시 DB로부터 데이터를 가져옵니다.
#     shop = Shop.objects.get(pk=pk)
#     return render(request, 'shop/shop_detail.html', {
#         'shop': shop,
#     })

shop_detail = DetailView.as_view(model=Shop)


@login_required
def shop_new(request):
    form_cls = ShopForm

    if request.method == "POST":  # "GET", "POST"
        form = form_cls(request.POST, request.FILES)
        if form.is_valid():
            shop = form.save()
            return redirect(shop)
    else:
        form = form_cls()

    return render(request, 'shop/shop_form.html', {
        'form': form,
    })

shop_new_cbv = CreateView.as_view(
    model=Shop, form_class=ShopForm)

@login_required
def shop_edit(request, pk):
    # try:
    #     shop = Shop.objects.get(pk=pk)
    # except Shop.DoesNotExist:
    #     raise Http404  # django.http.Http404

    shop = get_object_or_404(Shop, pk=pk)

    form_cls = ShopForm

    if request.method == "POST":  # "GET", "POST"
        form = form_cls(request.POST, request.FILES, instance=shop)
        if form.is_valid():
            shop = form.save()
            return redirect(shop)
    else:
        form = form_cls(instance=shop)

    return render(request, 'shop/shop_form.html', {
        'form': form,
    })



shop_edit_cbv = UpdateView.as_view(
    model=Shop, form_class=ShopForm)

@login_required
def shop_delete(request, pk):
    shop = get_object_or_404(Shop, pk=pk)

    if request.method == "POST":
        shop.delete()
        return redirect('shop:index')

    return render(request, 'shop/shop_confirm_delete.html', {'shop':shop,})

shop/templates/shop/layout.html
{% extends "layout.html" %}

{% block page_title %}
    알라딘 서점 
{% endblock %}

shop/templates/shop/shop_confirm_delete.html
<h1>
{{shop}} 을 삭제하시겠습니까?
</h1>


<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value ="삭제하시겠습니까?"/>
</form>

shop/templates/shop/shop_detail.html
{% extends "shop/layout.html" %}

{% block content %}
    <div class="container">
        <div class="col-sm-12">
            <h1>{{ shop }}</h1>

            {{ shop.desc }} |
            {{ shop.address }}

            {% if shop.photo %}
                <img src="{{ shop.photo.url }}" />
            {% endif %}

            <hr/>
            <a href="{% url "shop:index" %}" class="btn btn-primary">목록으로</a>
            <a href="{% url "shop:shop_edit" shop.id %}" class="btn btn-success">수정</a>
            <a href="/shop/{{ shop.id }}/delete/" class="btn btn-danger">삭제</a>

        </div>
    </div>

{% endblock %}

shop/templates/shop/shop_form.html
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" />
</form>

shop/templates/shop/shop_list.html
{% extends "shop/layout.html" %}

{% block content %}
    <div class="container">
        <div class="card-group">
            {% for shop in shop_list %}
                <div class="col-sm-4 mb-3">
                    <div class="card">
                        <img src="https://mblogthumb-phinf.pstatic.net/20150701_201/whdrnr95_1435721605440cJvNE_JPEG/DSC_0035.jpg?type=w2" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">
                                <a href="{% url "shop:shop_detail" shop.id %}">
                                    #{{ shop.id }}. {{ shop.name }}
                                </a>
                            </h5>
                            {% if shop.address %}
                                <p class="card-text">
                                    {{ shop.address }}
                                </p>
                            {% endif %}
                            {% if shop.desc %}
                                <p class="card-text">
                                    {{ shop.desc }}
                                </p>
                            {% endif %}
                            <p class="card-text">
                                <small class="text-muted">
                                    {{ shop.created_at }}
                                </small>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <a href="{% url "shop:shop_new" %}" class="btn btn-primary">새 가게 등록</a>
    </div>
{% endblock %}